spring:
  application:
    name: member-api
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    username: db_jsh
    password: Yliu
    url: jdbc:mysql://39.105.143.94:3366/db_jsh?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    service-registry:
      auto-registration:
        enabled: false
server:
  port: 8080